# -*- coding: utf-8 -*-
"""Nutrient Predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17sATlFbICor0r1qa4U90gx-8XRQ6UNYl
"""

# ============================================
# 🧠 DISH → NUTRITION ML MODEL (FULL PIPELINE)
# ============================================

# -------------------------------
# STEP 1: IMPORT LIBRARIES
# -------------------------------
import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.feature_extraction.text import TfidfVectorizer


# -------------------------------
# STEP 2: LOAD DATASET
# -------------------------------
# Upload your dataset in Colab first

df = pd.read_csv("food.csv")  # <-- change filename

print("Dataset Loaded:", df.shape)
print(df.head())


# -------------------------------
# STEP 3: DATA CLEANING
# -------------------------------
# Rename columns if needed (adjust based on your dataset)

df.rename(columns={
    "Dish Name": "dish",
    "Calories (kcal)": "calories",
    "Carbohydrates (g)": "carbs",
    "Protein (g)": "protein",
    "Fats (g)": "fat"
}, inplace=True)
# Drop missing values
df.dropna(inplace=True)

# Convert to lowercase
df["dish"] = df["dish"].str.lower().str.strip()

# Remove duplicates
df.drop_duplicates(subset=["dish"], inplace=True)


# -------------------------------
# STEP 4: FEATURE ENGINEERING (TF-IDF)
# -------------------------------
vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(df["dish"])


# -------------------------------
# STEP 5: TARGET VARIABLES
# -------------------------------
y = df[["calories", "protein", "fat", "carbs"]]


# -------------------------------
# STEP 6: TRAIN-TEST SPLIT
# -------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


# -------------------------------
# STEP 7: TRAIN MODEL
# -------------------------------
model = RandomForestRegressor()

model.fit(X_train, y_train)


# -------------------------------
# STEP 8: EVALUATION
# -------------------------------
y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)

print("\nModel Performance:")
print("MAE:", mae)


# -------------------------------
# STEP 9: SAVE MODEL
# -------------------------------
joblib.dump(model, "dish_nutrition_model.pkl")
joblib.dump(vectorizer, "dish_vectorizer.pkl")

print("\n✅ Models saved successfully!")


# -------------------------------
# STEP 10: TEST PREDICTION
# -------------------------------
test_dish = ["paneer dosa"]

vec = vectorizer.transform(test_dish)

prediction = model.predict(vec)[0]

print("\nPrediction for:", test_dish[0])
print("Calories:", round(prediction[0], 2))
print("Protein:", round(prediction[1], 2))
print("Fat:", round(prediction[2], 2))
print("Carbs:", round(prediction[3], 2))


# -------------------------------
# STEP 11: DOWNLOAD MODELS
# -------------------------------
from google.colab import files

files.download("dish_nutrition_model.pkl")
files.download("dish_vectorizer.pkl")