# -*- coding: utf-8 -*-
"""Recommendation_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i8633GlQ44LZrRErlTD1LJfGv9_D3LH0
"""

import pandas as pd

df = pd.read_csv(
    "RAW_recipes.csv",
    engine="python",
    on_bad_lines="skip"
)

print("Loaded rows:", len(df))
df.head()

df = df[["name", "ingredients", "nutrition"]]

df["ingredients"] = df["ingredients"].apply(lambda x: " ".join(eval(x)))

df["nutrition"] = df["nutrition"].apply(lambda x: eval(x))

nutrition_cols = ["calories", "fat", "sugar", "sodium", "protein", "sat_fat", "carbs"]

nutrition_df = pd.DataFrame(df["nutrition"].tolist(), columns=nutrition_cols)

df = pd.concat([df, nutrition_df], axis=1)

df.drop("nutrition", axis=1, inplace=True)

df = df.dropna()
df = df.drop_duplicates()

df = df.sample(2000, random_state=42)



df.rename(columns={"name": "recipe_name"}, inplace=True)

df.to_csv("final_recipes.csv", index=False)

import pandas as pd

df = pd.read_csv("final_recipes.csv", engine="python", on_bad_lines="skip")

# select only needed columns
df = df[["recipe_name", "ingredients"]]

# ❌ NO eval needed here

# clean
df = df.dropna().drop_duplicates()

# reduce size (important)
df = df.sample(2000, random_state=42)

df.head()

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words="english")

X = vectorizer.fit_transform(df["ingredients"])

from sklearn.neighbors import NearestNeighbors

model = NearestNeighbors(
    n_neighbors=5,
    metric="cosine"
)

model.fit(X)

def recommend_recipes(pantry_items):

    # convert pantry list → string
    pantry_str = " ".join(pantry_items)

    # convert to vector
    pantry_vec = vectorizer.transform([pantry_str])

    # find similar recipes
    distances, indices = model.kneighbors(pantry_vec)

    results = []

    for i in indices[0]:
        results.append(df.iloc[i]["recipe_name"])

    return results

recommend_recipes(["milk", "banana"])

import joblib

joblib.dump(model, "recipe_knn.pkl")
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")