# -*- coding: utf-8 -*-
"""Recommendation ENgine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N5UZHszuLEN0zOgTjWBKqNWxBETlxhij
"""

import pandas as pd

# Load dataset
df = pd.read_csv("Cleaned_Indian_Food_Dataset.csv")

# Select only needed columns
df = df[[
    "TranslatedRecipeName",
    "TranslatedIngredients",
    "Cuisine",
    "URL",
    "image-url"
]]

# Drop missing values
df.dropna(inplace=True)

# Rename columns
df.rename(columns={
    "TranslatedRecipeName": "recipe_name",
    "TranslatedIngredients": "ingredients"
}, inplace=True)

# Clean ingredients
df["ingredients"] = df["ingredients"].str.lower().str.replace(",", " ")

# Optional: filter only Indian
df = df[df["Cuisine"].str.contains("Indian", case=False)]

# Reduce size (important for speed)
df = df.sample(n=1500, random_state=42)

# Save cleaned data
df.to_csv("recipes_cleaned.csv", index=False)

print("✅ Cleaned dataset ready:", df.shape)

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
import joblib

# Load cleaned dataset
df = pd.read_csv("recipes_cleaned.csv")

# Create TF-IDF vectorizer
vectorizer = TfidfVectorizer()

# Train model
tfidf_matrix = vectorizer.fit_transform(df["ingredients"])

# Save everything
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")
joblib.dump(tfidf_matrix, "tfidf_matrix.pkl")
joblib.dump(df, "recipes_df.pkl")

print("✅ TF-IDF model trained and saved!")

import joblib
from sklearn.metrics.pairwise import cosine_similarity

# Load models
vectorizer = joblib.load("tfidf_vectorizer.pkl")
tfidf_matrix = joblib.load("tfidf_matrix.pkl")
recipes_df = joblib.load("recipes_df.pkl")

# Example pantry
pantry_items = ["tomato", "rice", "onion"]

# Convert to text
pantry_text = " ".join(pantry_items)

# Convert to vector
pantry_vec = vectorizer.transform([pantry_text])

# Compare
scores = cosine_similarity(pantry_vec, tfidf_matrix).flatten()

# Top recipes
top_indices = scores.argsort()[-5:][::-1]

# Output
recommended = recipes_df.iloc[top_indices][
    ["recipe_name", "Cuisine", "URL"]
]

print(recommended)