# -*- coding: utf-8 -*-
"""Wastage_predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dcZ7CZEB1Tg5d6v8kn1RvMwwqbPnCc2C
"""

# ============================================
# SMART FOOD WASTE MANAGEMENT - FINAL ML PIPELINE
# ============================================

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import r2_score, mean_absolute_error, accuracy_score
from sklearn.pipeline import Pipeline
import joblib

# ============================================
# STEP 1: LOAD DATA
# ============================================

df = pd.read_csv("wastage.csv")

print("Dataset Loaded:", df.shape)

# ============================================
# STEP 2: PREPROCESSING
# ============================================

df.rename(columns={
    "Food Category": "item_type",
    "Total Waste (Tons)": "total_waste",
    "Avg Waste per Capita (Kg)": "waste_per_capita",
    "Population (Million)": "population"
}, inplace=True)

# Fill missing values
df.fillna(df.median(numeric_only=True), inplace=True)

# Convert tons → kg
df["total_waste_kg"] = df["total_waste"] * 1000

# Waste per person
df["waste_per_person"] = df["total_waste_kg"] / (df["population"] * 1e6)

# Simulate realistic household features
np.random.seed(42)
df["family_size"] = np.random.randint(2, 6, len(df))
df["food_quantity"] = df["family_size"] * np.random.uniform(1, 3, len(df))
df["storage_days"] = np.random.randint(1, 10, len(df))

# Final target
df["food_waste_kg"] = df["waste_per_person"] * df["family_size"]

# ============================================
# STEP 3: ENCODING
# ============================================

le = LabelEncoder()
df["item_type"] = le.fit_transform(df["item_type"])

# ============================================
# STEP 4: REGRESSION MODELS (WASTE PREDICTION)
# ============================================

X = df[["family_size", "food_quantity", "storage_days", "item_type"]]
y = df["food_waste_kg"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# 🔹 Linear Regression
lr = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LinearRegression())
])
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

print("\n--- Linear Regression ---")
print("R2:", r2_score(y_test, y_pred_lr))
print("MAE:", mean_absolute_error(y_test, y_pred_lr))

# 🔹 Random Forest (BEST MODEL 🔥)
rf = RandomForestRegressor()
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("\n--- Random Forest Regression ---")
print("R2:", r2_score(y_test, y_pred_rf))
print("MAE:", mean_absolute_error(y_test, y_pred_rf))

# ============================================
# STEP 5: CREATE RISK LABEL
# ============================================

def risk_label(waste, qty):
    ratio = waste / qty
    if ratio < 0.3:
        return 0
    elif ratio <= 0.6:
        return 1
    else:
        return 2

df["risk"] = [
    risk_label(w, q) for w, q in zip(df["food_waste_kg"], df["food_quantity"])
]

# ============================================
# STEP 6: CLASSIFICATION MODELS
# ============================================

X_cls = df[["family_size", "food_quantity", "storage_days", "item_type"]]
y_cls = df["risk"]

X_train, X_test, y_train, y_test = train_test_split(X_cls, y_cls, test_size=0.2)

# 🔹 Decision Tree
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

print("\n--- Decision Tree ---")
print("Accuracy:", accuracy_score(y_test, y_pred_dt))

# 🔹 Random Forest Classifier (BEST 🔥)
rf_cls = RandomForestClassifier()
rf_cls.fit(X_train, y_train)

y_pred_rf_cls = rf_cls.predict(X_test)

print("\n--- Random Forest Classifier ---")
print("Accuracy:", accuracy_score(y_test, y_pred_rf_cls))

# ============================================
# STEP 7: SAVE BEST MODELS
# ============================================

joblib.dump(rf, "waste_model.pkl")       # regression
joblib.dump(rf_cls, "risk_model.pkl")    # classification
joblib.dump(le, "encoder.pkl")

print("\n✅ Models saved successfully!")

