# -*- coding: utf-8 -*-
"""Wastage_predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dcZ7CZEB1Tg5d6v8kn1RvMwwqbPnCc2C
"""

# ============================================
# SMART FOOD WASTE MANAGEMENT - FULL PIPELINE
# ============================================

# STEP 1: Upload Dataset
from google.colab import files

# STEP 2: Import Libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import r2_score, mean_absolute_error
import joblib

# STEP 3: Load Dataset (replace filename if needed)
df = pd.read_csv("wastage.csv")

print("Dataset Loaded:", df.shape)
print(df.head())

# ============================================
# STEP 4: PREPROCESSING
# ============================================

# Rename columns
df.rename(columns={
    "Food Category": "item_type",
    "Total Waste (Tons)": "total_waste",
    "Avg Waste per Capita (Kg)": "waste_per_capita",
    "Population (Million)": "population",
    "Household Waste (%)": "household_pct"
}, inplace=True)

# Fill missing values
df.fillna(df.median(numeric_only=True), inplace=True)

# Convert tons → kg
df["total_waste_kg"] = df["total_waste"] * 1000

# Convert to household-level
df["waste_per_person"] = df["total_waste_kg"] / (df["population"] * 1e6)

# Simulate family size
np.random.seed(42)
df["family_size"] = np.random.randint(2, 6, len(df))

# Final waste at household level
df["food_waste_kg"] = df["waste_per_person"] * df["family_size"]

# Create additional features
df["food_quantity"] = df["family_size"] * np.random.uniform(1, 3, len(df))
df["storage_days"] = (df["waste_per_capita"] / 10).astype(int)

# Select final dataset
df_model = df[[
    "family_size",
    "food_quantity",
    "storage_days",
    "item_type",
    "food_waste_kg"
]]

# ============================================
# STEP 5: ENCODING
# ============================================

le = LabelEncoder()
df_model["item_type"] = le.fit_transform(df_model["item_type"])

# ============================================
# STEP 6: LINEAR REGRESSION MODEL
# ============================================

X = df_model.drop("food_waste_kg", axis=1)
y = df_model["food_waste_kg"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

y_pred = lr_model.predict(X_test)

print("\n--- Linear Regression ---")
print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))

# ============================================
# STEP 7: RISK CLASSIFIER
# ============================================

def risk_label(waste, qty):
    ratio = waste / qty
    if ratio < 0.3:
        return 0   # LOW
    elif ratio <= 0.6:
        return 1   # MEDIUM
    else:
        return 2   # HIGH

df_model["risk"] = [
    risk_label(w, q) for w, q in zip(df_model["food_waste_kg"], df_model["food_quantity"])
]

X_cls = df_model.drop(["food_waste_kg", "risk"], axis=1)
y_cls = df_model["risk"]

X_train, X_test, y_train, y_test = train_test_split(X_cls, y_cls, test_size=0.2)

dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)

print("\n--- Decision Tree ---")
print("Accuracy:", dt_model.score(X_test, y_test))

# ============================================
# STEP 8: SAVE MODELS
# ============================================

joblib.dump(lr_model, "waste_model.pkl")
joblib.dump(dt_model, "risk_model.pkl")
joblib.dump(le, "encoder.pkl")

print("\nModels saved successfully!")

# ============================================
# STEP 9: DOWNLOAD MODELS
# ============================================

files.download("waste_model.pkl")
files.download("risk_model.pkl")
files.download("encoder.pkl")

